/*
 * Permanent Downunder Voices Social Issues editorial bank.
 *
 * These are editorial angles, not claims or pre-written conclusions.
 * The generator may use an angle only when current supplied news
 * material provides reliable facts and a genuine source URL.
 */
export const SOCIAL_ISSUES_EDITORIAL_TOPICS = [
  "Why working poverty is growing despite full-time employment in Australia",
  "Why working poverty is growing despite full-time employment in New Zealand",
  "Child poverty and the hidden cost of going without essentials",
  "Food-bank demand and what it reveals about household hardship",
  "The widening wealth gap between property owners and renters",
  "Regional poverty beyond the major-city headlines",
  "Single parents carrying the sharpest edge of the cost-of-living crisis",
  "Older people choosing between food, power and medicine",
  "Disability, poverty and the extra cost of everyday life",
  "Energy poverty and households afraid to use heating or cooling",
  "Grocery prices and whether competition is working for ordinary families",
  "Transport poverty and the cost of reaching work, school and healthcare",
  "Debt, buy-now-pay-later services and families living week to week",
  "Tax settings and whether low-income households receive a fair deal",
  "Emergency relief funding and whether it matches real community need",
  "Asian migrant workers facing underpayment in Australia",
  "Asian migrant workers facing underpayment in New Zealand",
  "Visa dependence and the power imbalance between migrant workers and employers",
  "Racial discrimination in recruitment and hiring",
  "Racial barriers to promotion and management roles",
  "Foreign qualifications being undervalued despite labour shortages",
  "Migrant women facing combined wage, visa and workplace disadvantage",
  "Temporary migrants afraid to report unsafe working conditions",
  "Employer-sponsored visas and the risk of coercion or retaliation",
  "Language barriers used to deny workers their rights",
  "Migrant exploitation in hospitality, cleaning and care work",
  "Migrant exploitation in construction, agriculture and seasonal work",
  "Racism in rental housing and access to accommodation",
  "Whether government migrant-worker protections work in practice",
  "The human cost of prolonged visa uncertainty",
  "The pay gap between frontline workers and senior executives",
  "Blue-collar wages compared with white-collar salary growth",
  "Why essential workers remain underpaid after public praise fades",
  "Wage theft enforcement and whether penalties deter employers",
  "Unpaid trial shifts and insecure workers",
  "Sham contracting and workers denied employee protections",
  "Labour-hire arrangements and who is accountable for underpayment",
  "Casualisation and the loss of predictable household income",
  "Gender pay gaps inside low-paid industries",
  "Racial pay gaps and the lack of transparent reporting",
  "Executive bonuses during layoffs and wage restraint",
  "Public-sector contractor pay compared with permanent staff pay",
  "Overtime, unpaid preparation and work performed off the clock",
  "Union representation for migrant and insecure workers",
  "Salary transparency as a tool against discrimination",
  "International student tuition fees in Australian universities",
  "International student tuition fees in New Zealand universities",
  "Whether international students receive fair value for high fees",
  "University dependence on international student revenue",
  "International student accommodation costs in Australian cities",
  "International student accommodation costs in New Zealand cities",
  "Overcrowding and unsafe housing among international students",
  "Student visa work limits and vulnerability to exploitation",
  "Unpaid placements and the financial burden on students",
  "Education-agent commissions and whether students receive independent advice",
  "Unexpected university charges beyond advertised tuition fees",
  "Course quality, large classes and support for international students",
  "Mental-health support for students living far from home",
  "International graduates, post-study visas and uncertain pathways",
  "Whether universities treat international students as students or revenue",
  "Homelessness among workers who have jobs",
  "Emergency housing rules and families falling through the gaps",
  "Rental affordability in Australia’s major cities",
  "Rental affordability in New Zealand’s major cities",
  "Social-housing waiting lists and the cost of delay",
  "Young people locked out of secure housing",
  "Domestic-violence survivors facing homelessness",
  "Overcrowded housing and preventable health problems",
  "Access to GPs and the price of delayed healthcare",
  "Hospital waiting times and their impact on low-income families",
  "Dental care becoming a luxury for ordinary households",
  "Mental-health services and the gap between promises and access",
  "Rural communities travelling long distances for essential care",
  "School costs that make supposedly free education unaffordable",
  "Digital exclusion and access to government and essential services",
  "Charity chief executive salaries compared with frontline worker pay",
  "Charity executive expenses, travel and luxury benefits",
  "How much of each donated dollar reaches people in need",
  "Government grants to charities and the standard of public accountability",
  "Fundraising costs and whether donors receive clear information",
  "Large charity reserves while community need keeps growing",
  "Charity branding budgets compared with direct assistance",
  "Board independence and conflicts of interest in charities",
  "Related-party contracts inside not-for-profit organisations",
  "Charity property portfolios and whether assets serve the mission",
  "Religious charities receiving public money and meeting public standards",
  "Small community charities competing with large corporate organisations",
  "Frontline charity workers facing low wages and burnout",
  "Volunteer labour supporting highly paid charity management",
  "Measuring whether charity programmes produce lasting results",
  "Government outsourcing social services without adequate oversight",
  "Public money, private providers and accountability for failed services",
  "Consultant spending while frontline services face cuts",
  "Policies announced without funding for practical delivery",
  "Community consultation that happens after decisions are effectively made",
  "Discrimination complaints and whether enforcement is strong enough",
  "Whistleblower protection for workers exposing social harm",
  "Indigenous and Māori disadvantage beyond political slogans",
  "Whether economic growth improves life for the poorest households",
  "What fairness should mean in Australia and New Zealand today"
] as const

export function buildEditorialTopicBank(): string {
  return SOCIAL_ISSUES_EDITORIAL_TOPICS
    .map(
      (topic, index) =>
        `${index + 1}. ${topic}`,
    )
    .join('\n')
}
